// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1xD74AjcPJDImZ-bczBmh_3WBVYtVFXs',
    appId: '1:71104541407:web:804f66c648d9c7434f2f6a',
    messagingSenderId: '71104541407',
    projectId: 'bookshop-11665',
    authDomain: 'bookshop-11665.firebaseapp.com',
    storageBucket: 'bookshop-11665.firebasestorage.app',
    measurementId: 'G-SNCZ9L1Z2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgfO-tblMQBXLK989Q4O92eXW_Y6A68p0',
    appId: '1:71104541407:android:ca39f992383c67a54f2f6a',
    messagingSenderId: '71104541407',
    projectId: 'bookshop-11665',
    storageBucket: 'bookshop-11665.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgrKDCfAGkijpqqST6anZlHW0sUxbZYRE',
    appId: '1:71104541407:ios:165b1027c03928254f2f6a',
    messagingSenderId: '71104541407',
    projectId: 'bookshop-11665',
    storageBucket: 'bookshop-11665.firebasestorage.app',
    iosBundleId: 'com.example.bookshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgrKDCfAGkijpqqST6anZlHW0sUxbZYRE',
    appId: '1:71104541407:ios:165b1027c03928254f2f6a',
    messagingSenderId: '71104541407',
    projectId: 'bookshop-11665',
    storageBucket: 'bookshop-11665.firebasestorage.app',
    iosBundleId: 'com.example.bookshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1xD74AjcPJDImZ-bczBmh_3WBVYtVFXs',
    appId: '1:71104541407:web:956186941111a53c4f2f6a',
    messagingSenderId: '71104541407',
    projectId: 'bookshop-11665',
    authDomain: 'bookshop-11665.firebaseapp.com',
    storageBucket: 'bookshop-11665.firebasestorage.app',
    measurementId: 'G-KDG3LPQMTS',
  );
}
